---  
- name: Set SNMP Community
  uri:
    url: "{{ bsn_url }}/data/controller/os/config/global/snmp"
    method: PUT
    body_format: json
    body:
      community: "{{ bsn_snmp_secret }}"
    headers:
      Cookie: "{{ bsn_cookie }}"
    status_code: 204
    validate_certs: "{{ bsn_validate_certs }}"