---
- name: get data and parse output
  include_tasks: "{{ role_path }}/tasks/helpers/parse_fact.yml"
  vars:
    bsn_command: "{{ item.command }}"
    bsn_parser: "{{ item.parser }}"
  loop: "{{ lookup('file', role_path + '/vars/get_facts_map.yml') | from_yaml }}"
  when: bsn_get_facts_subset | intersect(item.groups)

